### ISSUE TITLE
Docs: explain importance of `/public` for asset handling by Vite

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#100]
## What feature were you trying to use?

I was promised I could use any existing 11ty functionality without issue. However, I found some assets getting unexpectedly trashed during production builds. To quote @AleksandrHovhannisyan:

> I'm wondering why files like `someFile.liquid` don't get written. e.g.:
```
---
permalink: /robots.txt
eleventyExcludeFromCollections: true
excludeFromSitemap: true
---
User-agent: *
Sitemap: {{ "sitemap.xml" | toAbsoluteUrl }}
```

> More context—I see this in the output:

```
[11ty] Writing .11ty-build-DcNVBN/robots.txt from ./src/robots.liquid
[11ty] Writing .11ty-build-DcNVBN/sitemap.xml from ./src/sitemap.liquid
```

> But then those files disappear. Not sure why they get written to a temp folder. 

## Where did our docs fail you?

Our docs fail to describe how production builds work in Slinkity, where we:
1. Write your 11ty build to a temporary builder
2. Use Vite to process that temporary build and output into the _intended_ output folder

This causes a nasty issue for those using CLI tools to directly output to `_site`, since those resources will be clobbered by the Vite build (see #74). But in this case, Aleksandr is attempting to output static non-html resources using permalinks. In order for Vite to keep these assets around, Vite [requires you to use a `/public` directory](https://vitejs.dev/guide/assets.html#the-public-directory) to flag these resources as "do not touch"

## How can we improve?

Add a section for "gotchas coming from 11ty" and describe the purpose of the `/public` directory. In short, it is meant for resources that:
1. Vite should not touch
2. Are not referenced by _any_ files in your code. Ex. a directory of fonts doesn't need to exist in a `/public` directory since they're likely referenced by a CSS file. However, something like a `robots.txt` (which no file explicitly imports) _should_ be copied to a `/public` directory.

**Comment by AleksandrHovhannisyan** [comment]
Thanks, Ben! I was able to confirm that prefixing `/public` to the permalinks fixes the issue 👍
