### ISSUE TITLE
Docs redesign - table of contents

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#104]
We currently 

**Out of scope:** actual dev work. This is a design ticket only!

## Initial design exploration

I've found 2 different approaches to a table of contents. The first adds a second sidebar to the right of the documentation itself on desktop, and wraps this TOC to the top of the page for narrower devices.
- pros: optimizes for space, surfaces TOC on narrower screens instead of hiding behind a slide-out menu
- cons: must to scroll to top to find TOC on narrower screens

The second embeds the table of contents inside the side navigation. This appears just below your currently selected page
- pros: optimizes for space on narrower devices, avoids burying the lead on mobile
- cons: requires more scrolling to find nav items _below_ the TOC, less space efficient on desktop, hides TOC behind slide-out on mobile

[See screenshots of each approach on design exploration Figma 👉](https://www.figma.com/file/6sRiQ46r51pJKaVr11fB6I/Slinkity-docs?node-id=137%3A286)

## Goals
- [x] decide on which approach to use
- [ ] create mockups for all 3 breakpoints
- [ ] draft a dev issue

**Comment by brycewray** [comment]
@Holben888 FWIW, I recommend Option #1 (Astro's), your correctly noted "con" notwithstanding. IMHO, your likely visitors will be using desktops (or, at least, iPad Pro-sized tablets) for easier coding-while-reading endeavors. 😄

**Comment by nachtfunke** [comment]
There is no real distinction _needed_ between a dedicated TOC and a navigation in my opinion, because if split, both are essentially a split subset of the same information, which is content structure.

This can make total sense, of course, to soften some of the donwsides mentioned, but all of these downsides are symptoms of complex content structures.

How I see it, extracting a dedicated TOC can still happen at a point in time, where content has gotten complex enough where that would reap an actual benefit.

**Comment by Holben888** [comment]
@nachtfunke Well that's fair I suppose! But I think there's a benefit at a small scale too. Splitting them out, my eyes know to look to the left when jumping to different routes, and look to the right when browsing the current page. I also like showing the TOC at the top of the page on narrow screens so you can immediately jump to the right section (instead of sliding out a hidden menu).

Was trying to be impartial but yeah... I prefer Astro's approach as @brycewray mentioned 😁

**Comment by nachtfunke** [comment]
I wanted to ask if some of the original requirements have changed - otherwise I I'll orient myself after the mockups in the Figma file and the inspiration that was mentioned before!

**Comment by Holben888** [comment]
Requirements should be the same, yep! I’ll also mention that highlighting the current section as you scroll can be out of scope. Would like to see it at some point though 😄
