### ISSUE TITLE
Docs - introduce fluid type scaling

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#105]
## Where did our docs fail you?

We currently use whatever font sizes the browser provides by default across headings. This is _fine,_ but could cause inconsistent user experiences. We mostly avoided custom sizing because it's so dang hard to configure and scale across breakpoints.

## How can we improve?

I saw @AleksandrHovhannisyan's [fluid type scale](https://www.fluid-type-scale.com/) site and thought _"yes, that's the one!"_. I say we use this to configure our font sizes asap 😁 
- min font size: `14px`
- max font size: `18px` (our body font runs a bit smaller than other typefaces I've used, so `16px` doesn't feel right to me)

**Comment by ecarlisle** [comment]
Hi @Holben888 !
Just wanted to offer this up as I was looking into fluid typography with CSS `clamp()`. 
https://adrianroselli.com/2019/12/responsive-type-and-zoom.html

Short version. While `clamp()` is amazing, it may cause an Accessibility standards issue by disabling 200% zoom capability in a browser.

> Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality.

https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=144#resize-text

Hope this helps with decisions moving forth.

Thanks!

**Comment by bholmesdev** [comment]
Closing to keep our breakpoints as-is. Our docs have seen a lot of happy visitors since then, and ecarlisle raises a good point.
