### ISSUE TITLE
Prod builds have an empty style tag at the end of the body

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [slinkity/slinkity#109]
## Describe the bug

Not a bug per se, but possibly unwanted behavior: For dev builds, component-scoped styles (e.g., CSS modules or stylesheet imports inside a React component) get dumped inside a `style` tag at the end of the body per the `insertAdjacentHTML` logic in [`applyViteHtmlTransform`](https://github.com/slinkity/slinkity/blob/main/src/plugin/applyViteHtmlTransform.js#L16). In production builds, it looks like Vite actually pulls out that CSS into a proper stylesheet, so the body is left with a dangling empty style tag.

## To Reproduce
1. Go to https://www.fluid-type-scale.com/.
2. Inspect element.
3. Observe the empty `style` tag at the end of the body.
4. For dev builds, clone https://github.com/AleksandrHovhannisyan/fluid-type-scale-calculator, run `yarn` to install dependencies, and `yarn dev` to start the dev server. Observe the same style tag but with scoped CSS inside it.

## Expected behavior
Don't show the style tag if there's no children for it

## Screenshots

Prod:

![image](https://user-images.githubusercontent.com/19352442/147839118-971b21ae-4132-4965-a7c6-cf80bbb4dc89.png)

Dev:

![image](https://user-images.githubusercontent.com/19352442/147839130-ab554946-dd55-4d82-bc50-73daf6f74d58.png)

**Additional context**
Looks like this is the culprit: https://github.com/slinkity/slinkity/blob/main/src/plugin/applyViteHtmlTransform.js#L48

Seems like a simple fix—we can conditionally insert the style tag only if `pageStyles` isn't empty.

Would be happy to put in a PR, although I'm a bit intimidated by the prospect of testing this/mocking out viteSSR. Not sure what the best way to go about that would be.

**Comment by AndrewLeedham** [comment]
@AleksandrHovhannisyan @Holben888 and I have been rewriting this logic to remove `node-html-parser`, and I believe we have addressed it there, if not I'll double check before it gets merged and close this out with the PR.

**Comment by AleksandrHovhannisyan** [comment]
@AndrewLeedham Sounds good!
