### ISSUE TITLE
In static rendering mode, stylesheets imported into a component (ESM) are stripped out (prod only)

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [slinkity/slinkity#112]
## Describe the bug

Suppose you have a React component like this:

**`_includes/components/Test/index.jsx`**
```jsx
import styles from './styles.css';
const Test = () => <div/>;
```

with this CSS:

**`_includes/components/Test/styles.css`**
```css
div { background: white; }
```

And statically render it in Slinkity:

**`index.njk`**
```html
{% react 'components/Test/index', render='static' %}
```

In dev mode, this works perfectly and bundles the CSS as part of the final stylesheet.

In prod mode, the imported styles disappear.

## To Reproduce

1. Clone this repo: https://github.com/AleksandrHovhannisyan/slinkity-bug-112
2. Run `yarn` to install dependencies.
3. Run `yarn start` to start dev mode. Observe a white square (component-scoped CSS) on a black background (static global CSS).
4. Run `rm -rf _site` to purge output.
5. Run `yarn build` to build for prod.
6. Open `_site` and observe that the stylesheet only contains the global static CSS, not any of the component's CSS.

## Expected behavior
Statically imported CSS should be bundled in the final stylesheet.

## Additional context

- Disabling static rendering for the component fixes the issue.
- Observed with CSS, CSS modules, and Sass.

**Comment by Holben888** [comment]
Understood! We have updated the "partial support" status on CSS imports [here](https://slinkity.dev/docs/#feature-set), but this is an unexpected bug.

But I will say... I've spent months trying to find a solution at this point, and it is NOT easy to server render CSS files imported via ESM. The disconnect comes down to how components are rendered. When processing a JSX file with React's `renderToString`, it doesn't return what styles were used within that JSX file. So we need to either:
1. Crawl the entire dependency graph to find those imports
2. Syphon off CSS imports via a Vite plugin, and try to reconcile them later on (which can cause styles to bleed between pages)

Here's [one of several Vite issue threads](https://github.com/vitejs/vite/issues/1579#issuecomment-999297346) on the subject. Would love for someone to devote time to this!

**Comment by Holben888** [comment]
Update: [this solution](https://github.com/vitejs/vite/issues/2282#issuecomment-787049601) on a separate issue thread looks promising. Worth investigating 👀

**Comment by Holben888** [comment]
Another update: [I started a thread with Astro x Vite](https://canary.discord.com/channels/804011606160703521/903350112338735104/926884360244846602) to see how they handle this issue. To quote the behavior we're looking for:

> I want to achieve this flow:
> - I write a React component
> - I import a stylesheet into that React component: import './styles.css', import styles from './styles.module.css', etc
> - I apply that React component to some static template. I don't want to hydrate this component at all. Just pre-render it at build time.
> - See my component's HTML alongside that CSS I imported. Ideally, that CSS is slapped in a <style> tag just above my component

> ☝️ The trouble comes from that "no hydration" bit. If I don't send Component.jsx to the client, how can I inject that CSS onto the page?

**Comment by AleksandrHovhannisyan** [comment]
> When processing a JSX file with React's renderToString, it doesn't return what styles were used within that JSX file.

Oof, that's unfortunate; hope they can resolve this at the Vite level!

**Comment by Holben888** [comment]
@AleksandrHovhannisyan Well at this point, there _is_ a recommended solution: crawl all the submodules for the module you just rendered. It's just not-at-all fun to implement 😆 

I found a [discussion with Rich Harris on the Vite SSR discord](https://discord.com/channels/804011606160703521/804061937029218334/810901252862509067).

This [inspired this approach](https://github.com/brillout/vite-plugin-ssr/commit/debb9bdbc72d0674066541e39362810d7127b161#diff-5b728e58b78bfac491cdfdb37938c371dba95e164f42748bcec6e5c51db10faeR119-R137) in the Vite SSR project. I think this is the golden ticket, but it'll take some serious legwork to get going! We currently call `vite.build` for _every single module you partially hydrate._ I have a feeling this will be a performance bottleneck to address in the future. It also makes production builds especially difficult to parse together sadly.

**Comment by Holben888** [comment]
Welp, you sidetracked me @AleksandrHovhannisyan. Think I got it working 😁

**Comment by AleksandrHovhannisyan** [comment]
@Holben888 Lol, sorry to spoil your new year's!

**Comment by Holben888** [comment]
Ha, no problem! This problem's been looming over me for too long. Guess it took a year change to clear my head 😉

**Comment by AleksandrHovhannisyan** [comment]
Thanks a bunch for looking into this!
