### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#12]
**Is your feature request related to a problem? Please describe.**
I'm limited to using `.jsx` templates with React for interactive routes + shortcodes on my site. `.vue` files should be an option too!

**Describe the solution you'd like**

I would expect to get feature parity with existing `.jsx` files. We'll likely use Vue's single page components as a starting point to simplify scoped CSS compilation. 
- a `vue` shortcode to render components in existing templates, with the freedom to pass props: `{% vue 'components/Evan-tually.vue' 'render' 'static' %}`
- support for `.vue` extensions on page-level templates
  - a way for pass frontmatter to 11ty as part of the data cascade
  - a way to choose props you want the component to receive in the clientside bundle, [similar to `getProps`](https://slinkity.dev/docs/component-pages-layouts/)
- support for our 3 rendering modes:
  - `eager`: load our component on page load
  - `lazy`: load our component when scrolled to (note: the Vue library can still be loaded on page load!)
  - `static`: render our component to static HTML + CSS, no JavaScript shipped

**Describe alternatives you've considered**
Well, erm, React I guess 🙃

**Comment by Holben888** [comment]
This should get split out into a few "feature" issues once we get the build setup down!

**Comment by ajcwebdev** [comment]
## Vue Update

There's one final step on the journey of getting the build setup down. We need to make an API for "renderer" plugins.

### Renderer Plugins

Renderer plugins are framework-level, internal API that allow us to work on Vue support. Once we feel good about it, we can expose plugins as an option on some sort of `slinkity.config.js`. This will be roughly be based on Astro's [UI Renderer Reference](https://docs.astro.build/reference/renderer-reference).

**Comment by Holben888** [comment]
> ### Renderer Plugins
> Renderer plugins are framework-level, internal API that allow us to work on Vue support. Once we feel good about it, we can expose plugins as an option on some sort of `slinkity.config.js`. This will be roughly be based on Astro's [UI Renderer Reference](https://docs.astro.build/reference/renderer-reference).

Now an open issue! #55
