### ISSUE TITLE
Automate release note generation on npm releases

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#122]
## Is your feature request related to a problem? Please describe.
When releasing new Slinkity versions, it's easy to forget associated release notes. We began using GH's release feature as of v0.5.0 which resolves some of our problems. Still, I'd prefer a tool that:
1. Generates a changelog within the repo itself (GH releases are a GitHub specific feature)
2. Generate on new npm releases, rather than a separate menu

## Describe the solution you'd like
We had a few suggestions on the 11ty discord here:
> Have you tried out https://github.com/changesets/changesets/ ? I really like it for generating changelogs & it handles monorepos really well, which can be useful as renderers break out from the main project @mdarrik

> I used https://github.com/sindresorhus/np once for a package I published and I really liked it; it's basically a wrapper around npm publish that makes it easier to generate GitHub releases. @AleksandrHovhannisyan

I'd also like our generated changelog to be edit-able like any other repository file! It'd be nice to add our whiteboard update logs as they're uploaded 🙃 

## Describe alternatives you've considered
- GH releases, which comes with the few caveats I mentioned
- Manual release notes - a lot of overhead to maintain, not easy to find associated PRs for linking

**Comment by AndrewLeedham** [comment]
I've had success using https://github.com/intuit/auto. They have plugins for both GitHub Releases and NPM publishing. It also updates the CHANGELOG.md file in the repo, which can be edited manually if needed. Release notes are generated from PRs with specific labels for the type of update, and you can include additional notes.

**Comment by Holben888** [comment]
Update: after joining the [Astro](https://astro.build/) team, I've really gotten in-the-flow with changesets. I'll probably move forward with this library for my own familiarity. Really liking it so far!
