### ISSUE TITLE
Docs: color contrast for docs code samples

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [slinkity/slinkity#123]
(This issue doesn't really fit into any of the templates.)

I personally find it a little hard to read some of the code samples in the docs that use the purple color, e.g.: 

![image](https://user-images.githubusercontent.com/19352442/149520956-5feca49c-d130-4a72-8f37-e93a14199770.png)

Running `#F92AAC` (foreground) against `#2A2139` (darkest background in the gradient) fails for AA/AAA on regular text.

Using a brighter color might help make it more readable. Experimenting a bit, I found that `#ffbde7` looks sharper:

![image](https://user-images.githubusercontent.com/19352442/149521372-f0f23354-ead9-4c7b-8293-66fdbca73b71.png)

However, due to the gradient background, the contrast is a little worse for the text towards the bottom of the code sample than it is for the text towards the middle (where it uses the darker color).

Thoughts/ideas?

**Comment by Holben888** [comment]
Thanks for reporting this! We've been using the stock synthwave theme up until now, but I suspect we'll tweak the colors as part of our rebranding. I want to ditch that gradient background in particular in favor of our new purple theming (see #102). Will update once new branding is in

**Comment by Holben888** [comment]
Update: here's our new code snippets! I think it addresses the color contrast concern 😁 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/31811199/149626902-a933efaa-bc5d-4b09-8739-5322f00b8ae6.png">

Feel free to [browse the deploy preview](https://deploy-preview-126--slinkity.netlify.app/docs/config/) as well

**Comment by AleksandrHovhannisyan** [comment]
The new code blocks look great!
