### ISSUE TITLE
Output folder is emptied, but I am compiling my own assets and prefer not to empty

### ISSUE THREAD

**Issue by paulshryock** [slinkity/slinkity#137]
## Is your feature request related to a problem? Please describe.
When I run Slinkity, my output folder is emptied. I have other assets compiling into my output folder in parallel, and those are getting removed when I run Slinkity.

## Describe the solution you'd like
Instead of [passing `emptyOutDir: true` to Vite](https://github.com/slinkity/slinkity/blob/main/packages/slinkity/cli/vite.js#L88), this should be able to be overridden via CLI flag (e.g., `--clean=false` or `--doNotClean`).

## Describe alternatives you've considered
1. The alternative is probably to use Skinkity via JS API and wire up Vite manually with my own config. That seems doable, but a CLI flag would be much simpler.
2. Or, I just thought of this, maybe I can setup a local Vite config file that would override this? I haven't used Vite yet, but I can look into that as an alternative if needed.

## Additional context
I'm happy to code up a quick PR to add the CLI flag override.

**Comment by Holben888** [comment]
Hey @paulshryock! So I'll be honest: this is a much more nuanced issue beyond emptying the output directory. Vite actually removes any assets that are _not_ directly referenced by HTML files in your project.

I totally understand if you find this confusing. We have a couple issues set up to track this! Namely:
- #74 - discussing how to ensure images generated by 11ty image are present in the build output
- #114 - PR to document usage of a `/public` folder for other assets. This is nearly ready-to-merge, so you can check out our draft to see what solutions we offer

I'll close this issue as a duplicate. But if you feel there's more to the story we should track, I'm happy to re-open it
