### ISSUE TITLE
Improve Netlify deploy config

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#176]
## Is your feature request related to a problem? Please describe.

We recently switched to using the workspace version of Slinkity on our docs. This is great for dogfooding the latest Slinkity canary locally, but it causes problems with our Netlify deploy previews. Here's the problem we were having:
1. `pnpm` installs all necessary dependencies
2. While installing the doc dependencies, it discovers the Slinkity CLI doesn't exist yet. That's because the CLI is built _after_ everything is installed
3. The build fails because the CLI is built too late

[Sample deploy preview failure here](https://app.netlify.com/sites/slinkity/deploys/62094a0fab75090008098016)

Splitting out to two separate `npx pnpm` calls resolves the issue, since the `postinstall` script will run before the other workspace dependencies are resolved. Here's a quote from our `netlify.toml` 👇 
```toml
command = """\
    npx pnpm i --filter slinkity --store=node_modules/.pnpm-store &&\
    npx pnpm i --store=node_modules/.pnpm-store &&\
    npm run build\
    """
```

However, needing to `npx` install `pnpm` _twice_ seems overly complex. It would be nice to run a single CI script that orchestrates the installation and build ordering.

## Describe the solution you'd like

Here's a suggestion from @AlexMunoz based on Vite's config. Looks promising!

> maybe we can just have an extra Script for this task in package.json, like vitejs does https://github.com/vitejs/vite/blob/main/package.json#L34 
> ```
> ci:www: "run-s build www:build"  
> ```
> and then in [netlify.toml]
> 
> ```
> npx pnpm i --store=node_modules/.pnpm-store && npx pnpm -w run ci:www 
> ```

**Comment by AlexMunoz** [comment]
something that i just realized was that slinkity has been autmatically built by the prepare script rather than using the build script. 
I think it's better to have explicit defined steps rather than something that just runs after a package install, what do you think?

**Comment by Holben888** [comment]
@AlexMunoz Yeah I think so. I know Turborepo is a clean way to define CI steps from our `package.json`. Open to other suggestions though
