### ISSUE TITLE
"pathPrefix" get's ignored

### ISSUE THREAD

**Issue by leifniem** [slinkity/slinkity#181]
When configuring the eleventy option `pathPrefix` which prefixes paths (e.g. subfolder output), running slinkity compared to vanilla eleventy does stick to the unprefixed paths.

## To Reproduce
1. add `pathPrefix: '/foo/'` to `module.exports` of `.eleventy.js`
2. add urls with {{ link | url }} for the prefix to work eleventy
3. run build
4. see urls in output

## Expected behavior
The prefix should be at the beginning of each url

 - Windows 11
 - 0.6.1-canary.0
 - PowerShell through VS Code
 
 Eleventy docs regarding the option:
https://www.11ty.dev/docs/config/#deploy-to-a-subdirectory-with-a-path-prefix

**Comment by Holben888** [comment]
Ah, good callout! This has admittedly been missing since Slinkity started 😢 

It looks like we're passing the `pathprefix` flag to our `startEleventy` command as an option, so I'm curious why it's getting ignored. It may have to do with 11ty's JS API ignoring this flag but I'm not sure yet.

**Comment by Holben888** [comment]
Update: it seems 11ty itself ignores the `pathprefix` CLI option in production builds. Since Slinkity v0.8 will _remove_ the slinkity CLI, this shouldn't be an issue on Slinkity's end at least. Closing with a note to open an 11ty issue!
