### ISSUE TITLE
DEBUG=Eleventy* crashes slinkity

### ISSUE THREAD

**Issue by andystevenson** [slinkity/slinkity#186]
Huge fan of slinkity/vite and building website for a charity sports complex based on it.

```
package.json
....
    "start": "DEBUG=Eleventy* slinkity --serve --incremental",

```
Expected it to run and give me the eleventy debug output

```
> DEBUG=Eleventy* slinkity --serve --incremental

  Eleventy:EventBus Setting up global EventBus. +0ms
  Eleventy:UserConfig Resetting EleventyConfig to initial values. +0ms
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'time-require'
Require stack:
- /Users/andystevenson/dev/wwsc.club/node_modules/slinkity/lib/cli/index.js
    at Function.Module._resolveFilename...


```

Running on MacOS Monterey 12.2.1

```
package.json
...
  "devDependencies": {
    "@11ty/eleventy": "^1.0.0",
    "postcss": "^8.4.5",
    "postcss-custom-media": "^8.0.0",
    "postcss-jit-props": "^1.0.4",
    "sass": "^1.49.0",
    "slinkity": "^0.5.0"
  },

```

**Comment by Holben888** [comment]
Ah yep, I knew this issue would come back to haunt me. We purposefully _didn't_ support the DEBUG flag early on due to a number of complications. I'd be happy to revisit this if DEBUG is used by enough Slinkity users (like yourself). For now, it's probably worth noting as a gotcha in our docs.

**Comment by andystevenson** [comment]
Thanks and understood Ben, to be honest I had a separate weirdness in Eleventy Data Cascade that had me reach for this. Turns out to probably be a bug in eleventy.
I think the vast majority of eleventy users will never have to reach for DEBUG.
I am happy to close it for now. A warning in the docs is definitely the best way to go given the complications.

**Comment by Holben888** [comment]
Actually gonna re-open this to track that documentation update.

Future visitors to this issue: we need a note on the `DEBUG` flag [under our config page](https://slinkity.dev/docs/config/).

**Comment by andystevenson** [comment]
I created a PR to fix this.
Forgive me as I aborted the first PR I tried because I messed up the fork!
The one that is there is hopefully valid?

**Comment by Holben888** [comment]
Yep, thanks!
