### ISSUE TITLE
slinkity 0.5.0 drags in react-dom as a dependency even if you don't use it

### ISSUE THREAD

**Issue by andystevenson** [slinkity/slinkity#187]
I had a project running fine and after running npm update (to grab slinkity 0.5.0) I encountered the following.

npm start

```
package.json
...
"start": "BUILD='development' slinkity --serve --incremental",

```

Yielded the following error
```

...
Pre-bundling dependencies:
  @andystevenson/theme-toggle
  slinkity/client
(this will be run only when your dependencies or config have changed)
✘ [ERROR] Could not resolve "react-dom"

    node_modules/slinkity/client/renderer.js:2:21:
      2 │ import ReactDOM from 'react-dom'
        ╵                      ~~~~~~~~~~~

  You can mark the path "react-dom" as external to exclude it from the bundle, which will remove
  this error.
....

[11ty] Copied 25 files / Wrote 10 files in 0.75 seconds (75.0ms each, v1.0.0)
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] > Build failed with 1 error:
node_modules/slinkity/client/renderer.js:2:21: ERROR: Could not resolve "react-dom"

`Error` was thrown:
[11ty]     Error: Build failed with 1 error:
    node_modules/slinkity/client/renderer.js:2:21: ERROR: Could not resolve "react-dom"


```

Obviously didn't expect the crash.
I am using slinkity to build a pure eleventy/vite site not using react or any other framework.

Vite now drags in the following dependencies.
```

  slinkity/client
  react
  react/jsx-runtime
  react/jsx-dev-runtime
  (...and 1 more)
```

Which aren't used anywhere in my code.

**Comment by Holben888** [comment]
Good catch! This was obviously an oversight, but it will be a moot point with the release of 0.6.0.

The fix for 0.5.0 is fairly simple though; just need to remove `slinkity/client` from `optimizedDeps` if you don't have `react` or `react-dom` installed.

**Comment by andystevenson** [comment]
Thanks Ben. I'll go with the fix for now. I'm a few weeks off truly optimizing my build so happy to live with this for now. Looking forward to 0.6.0. Keep up the excellent work!

**Comment by Holben888** [comment]
@andystevenson oh sorry, that isn't a fix you should make as a user! I meant we'll need to remove that optimized dependency from our end. It's [just a one line change](https://github.com/slinkity/slinkity/blob/main/packages/slinkity/cli/vite.js#L75) I think. Happy to address this for 0.5.0 users.

**Comment by Holben888** [comment]
This is also a good first issue for new contributors. If you want to submit a PR, be my guest!
