### ISSUE TITLE
New partial hydration modes

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#20]
**Is your feature request related to a problem? Please describe.**
I want to have finer control over when my component is hydrated on the page. I expect [these 5 methods from Astro's partial hydration](https://docs.astro.build/core-concepts/component-hydration) to work:
- load: Hydrate when the DOM is finished parsing
- idle: Hydrate when the main thread is no longer busy (aka DOM is done parsing, and any JS _outside_ my component is finished running)
- visible: Hydrate when my component has scrolled into view
- media: Hydrate when a media query is met
- none: Never hydrate

**Describe the solution you'd like**
I'd like to see a new API similar to Astro's `client:property` helper. We'll use some new naming for Slinkity though:

**Prop name change:** hydrate (instead of Astro's `client`)
- this describes the "purpose" of the prop better than `client` in my opinion: to hydrate your static markup
- ties directly into the feature's name on our documentation: Partial Hydration
- hey, hydrate or diedrate am I right?

**Comparison of Astro and Slinkity syntax**

Astro:
```js
import ReactComponent from '...'
---

<ReactComponent client:visible />
```

Slinkity:
```md
{% react 'components/ReactComponent' hydrate="lazy" %}
```

**Value naming**

| Slinkity | Astro    |
| --------|-------|
| eager    | load     |
| lazy     | visible  |
| none     | [empty]  |

- we changed `visible` to `lazy` because a) `visible` could be associated with the `display` and `visibility` properties in CSS (which can cause confusion), and b) this feature is often compared to `lazy` image loading in the DOM. Yes, lazy is often an overloaded term in CS. But if we're going to choose a short and concise name, why not choose something similar to existing browser features?
- we also changed `load` to `eager` to add a yin to `lazy`'s yang. It also made less sense to use `load` after switching from `client` to `hydrate` for the prop name (i.e. `client:load` makes sense, but `hydrate="load"` doesn't as much)
- we allow `hydrate="none"` as a potential value, since we _will_ allow users to choose a default hydration method for their project (but no hydration _is_ the default!). Including a "none" allows users to override whatever default they've chosen to opt-out of hydration

**Handling idle, media, etc**

You may have noticed a few hydration modes like `idle`, `media`, and `client:only` are missing from that table. Well, we have a special plan for those... check out [this proposal](https://github.com/slinkity/slinkity/issues/20#issuecomment-906919414) in the comments 😄

**Comment by Holben888** [comment]
Glad to hear it @seancdavis! Answering those clarifications:

> 1. Does a lack of a `hydrate` prop mean the component will render statically and not hydrate?
> 
> ```
> {% react 'components/Footer' %}
> ```

That's the idea, yep! We actually use an opt-out model right now, but I want to move towards this opt-in model to mirror Astro's approach (and 11ty's ethos of "no JS bundles"). Still, I want to keep `hydrate="none"` as a valid option in case we allow global overrides for this behavior. For instance, you might say `hydrate="eager"` is the default _you_ prefer for all shortcodes in your project. You'll use `hydrate="none"` to opt-out in that case.

>  2. Are modifiers optional? (I assumed so because you said, "... you **could** attach modifiers ...") Meaning this would hydrate the component once it is within the viewport, even if the main thread is not idle?
> 
> ```
> {% react 'components/Footer' hydrate="lazy" %}
> ```

Exactly! I think this will lessen the learning curve too. eager vs. lazy is an easy concept for those already using, say, lazy image loading. You should only reach for modifiers _when the need arises,_ instead of using them because "you saw them in the docs and they look fancy."

**Comment by daKmoR** [comment]
I sort of have the same confusion around this

> Does a lack of a hydrate prop mean the component will render statically and not hydrate?

why does this mean only server render? why does it not mean only client render? and how would I get client render only?

I'm not sure if defining only `eager` and `lazy` as two main "entry points" makes sense 🤔
Why not eager and idle as two main "entry points"? 🤔

🤔🤔🤔

it seems the 3 fundamental "states" are exclusive:

- server (only render it server-side => do not ship any js [hopefully the default])
- client (do not touch server-side and ship js)
- hydrate (render server-side and at some point do loading + rendering on client-side)

For `server/client` there are no additional "options"... but for hydrate, there are multiple modifies you could combine

| Mode    | Option     | Description                                                                                                 |
| ------- | ---------- | ----------------------------------------------------------------------------------------------------------- |
| server  |            | render server-side and do not hydrate (default)                                                             |
| client  |            | do not touch server-side and render client side                                                             |
| hydrate | 👇         | render server-side and at some point do loading + rendering on client-side                                  |
|         | .onRender  | hydrate as soon as possible                                                                                 |
|         | .onIdle    | hydrate as soon there is a free slot in the main thread                                                     |
|         | .onDelay   | hydrate after x ms                                                                                          |
|         | .onMedia   | hydrate as soon as a media query is met                                                                     |
|         | .onVisible | hydrate as soon as component + optional padding becomes visible                                             |
|         | .onClick   | hydrate as you click on the element                                                                         |
|         | .onHover   | hydrate as you hover over the element + optional padding (click will trigger hover as well => touchscreens) |

| Example                                                                                 | Description                                                                                                       |
| --------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| `render-mode="server"`                                                                  | non interactive stuff like layouts or graphical components (= default)                                            |
| `render-mode="hydrate"`                                                                 | most components should just hydrate as soon there is a free slot in the main thread                               |
| `render-mode="hydrate:onIdle"`                                                          | same as 👆                                                                                                        |
| `render-mode="hydrate:onRender"`                                                        | above the fold element that should become interactive as soon as possible                                         |
| `render-mode="hydrate:onMedia(@media (max-width: 320px))"`                              | mobile burger menu that triggers a drawer for navigation (only hydrate on screens smaller then 320p)              |
| `render-mode="hydrate:onMedia(@media (min-width: 640px)).onClick"`                      | chart that only becomes interactive on desktop after a click                                                      |
| `render-mode="hydrate:onMedia(@media (prefers-reduced-motion: no-preference)).onClick"` | a visual animation that plays on click only if there is no prefers-reduced-motion                                 |
| `render-mode="hydrate:onVisible.onIdle"`                                                | heavy chart that becomes interactive when element becomes visible                                                 |
| `render-mode="hydrate:onVisible(100px)"`                                                | heavy chart that becomes interactive when element + 100px padding becomes visible                                 |
| `render-mode="client"`                                                                  | components that do something that can not be server rendered (for example need to access cookies or localStorage) |

sadly this does not prevent "useless" combinations like `render-mode="hydrate:onVisible.onClick.onHover"`.

this was a huge inspiration and it might happen sometime in the next major version of rocket 🤔

**Comment by Holben888** [comment]
Thanks for that incredibly thorough explanation @daKmoR! I was planning to explain our reasoning at first... but the more I look at this, the more I really like it.

One small critique would the phrasing on `render-mode="hydrate:onRender"`. Without reading the documentation, I'd be unsure what this means (how can I render on render?) I'd prefer something more recognizable like `render-mode="hydrate:asap"`. A little informal yes, but it immediately tells me "ah, we're expediting the hydration here."

I'll cross-share to our 11ty discord channel to see how the community feels. I [invite you to join us there](https://discord.gg/GBkBy9u#plugin-slinkity) as well 😁

**Comment by daKmoR** [comment]
sweet - indeed `onRender` was a horrible name - just couldn't come up with something "nicer"... `hydrate:onClientLoad` sounds definitely nicer... I actually like the `hydrate:asap` as well... 🤔 but then acronyms can always be tricky if you don't know them 🙈

maybe we can come up with a better name for `renderMode` 🤔
how about `sch="hydrate:onVisible"` standing for server, client, hydrate... muhaha ok better not... yeah can't come up with a better name 🙈

**Comment by Holben888** [comment]
Alright, meant to summarize our discord conversation relating to the above ☝️ 
Made a few notable changes to our modes thanks to @daKmoR's suggestions!

First off, we _will_ be keeping the `hydrate` flag around as opposed to `renderMode`. Hydration has been the main buzzword around the islands architecture story, so I'd like to keep it for familiarity's sake. However, We're ditching some elements of my proposal entirely:
1. `eager` and `lazy` are _dead!_ Astro's taking off like a rocket as you might expect, so I'd like to use their directive naming for more familiarity
2. We're adding a new flag you can use instead of `hydration` should you opt-out of SSR: `renderWithoutSSR`. This is purposefully verbose to (hopefully) discourage people from using it. Even if you're just SSR-ing a loading spinner, that's always better than a white void 🤷 

Here's the full spectrum of options:

- `hydrate|renderWithoutSSR=true` - simplest use case we expect most to use. Maps to `onClientLoad`
- `hydrate|renderWithoutSSR="onClientLoad"` - After the page has mounted _and_ HTML is parsed. Same as using the `async` tag
- `hydrate|renderWithoutSSR="onClientIdle"` - After HTML is parsed _and_ the main thread is idle
- `hydrate|renderWithoutSSR="onComponentVisible"` - When component is visible on the page
- `hydrate|renderWithoutSSR="onClientMedia(max-width: 500px)"` - When a media query is satisfied

You'll notice that you can still use flags like `onComponentVisible` when using `renderWithoutSSR`. This is intentional! I could still see the use case for lazy loading a non-SSR'd component to save on time-to-first-bite. This is a feature that Astro's sadly lacking, lacking due to their directive naming scheme. Not to brag but... I think we have the better directive naming here 😉

**Comment by Holben888** [comment]
Addendum on stacking partial hydration modes: the dot `.` syntax from the previous proposal was a bit confusing. i.e. is it an "and" or an "or?" For clarity, what if we just... use `&&` and `||`? Example:

- `hydrate="onComponentVisible || onClientMedia(...)"`
