### ISSUE TITLE
Unit test core functionality

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#21]
**Is your feature request related to a problem? Please describe.**
We have quite a few core + helper functions in our `reactPlugin` directory that could use testing. At the moment, we just have _one test total_ in our `utils` directory 🙃 

**List of tests left to write**
- [x] `reactPlugin/toRendererHtml` - unit tests
- [x] `reactPlugin/index` -> `add-react-renderer-script` HTML transform - snapshot tests
- [x] `reactPlugin/addShortcode` -> `argsArrayToPropsObj` Shortcode props reader - unit tests
- [x] `reactPlugin/toFormattedDataForProps` 11ty data converter - unit tests
~~- [ ] `utils/toUnixPath` - unit tests~~ This helper no longer exists!

**Comment by paulshryock** [comment]
Hi @Holben888 👋 , I've been checking out Slinkety and would be willing to contribute some unit tests to increase coverage and help wrap up this ticket. I setup a PR #136 to start with a simple unit test for one of the utils.

**Comment by Holben888** [comment]
Awesome, thanks @paulshryock! Just merged that test 👍 

I think `toFormattedDataForProps` is the last "must-have" unit test on my list. After that, I plan to detail some end-to-end tests I'd like to see after our next release. I'll mention this thread once that issue's up!

**Comment by Holben888** [comment]
Well @paulshryock, looks like you cleared out that unit test list and then some. I'm happy to close out this issue now, but feel free to flag room for future test coverage!

I also noticed you screenshotting a test coverage tool over yours. Is this something a GH bot could help us with as well?

**Comment by paulshryock** [comment]
> Well @paulshryock, looks like you cleared out that unit test list and then some. I'm happy to close out this issue now, but feel free to flag room for future test coverage!
> 
> I also noticed you screenshotting a test coverage tool over yours. Is this something a GH bot could help us with as well?

@Holben888 I was just passing the `--coverage` flag to Jest. Yeah, there are ways to set minimum test coverage percentages which would be required before PR's can merge, by a GitHub Action, for example. Is that what you mean? Or husky pre-commit hooks for stuff like that can be nice as well.
