### ISSUE TITLE
Broken link in README and missing site URL

### ISSUE THREAD

**Issue by SteveALee** [slinkity/slinkity#224]
## What feature were you trying to use?

Get up to date by reading the README

## How can we improve?

- Fix broken link - `[partial hydration helpers](https://github.com/slinkity/slinkity/blob/main/docs/partial-hydration).`
- Add slinkey.dev as the Repo URL (in settings)

**Comment by bholmesdev** [comment]
Thanks for the catch @SteveALee! I'm a bit confused by "Add slinkity.dev as the Repo URL" though. We already have this set as the "homepage" in our `package.json`. Where else should this be added?

**Comment by SteveALee** [comment]
Github has a setting for entering the related site uri. It might br part of the repo description.

**Comment by bholmesdev** [comment]
Ah gotcha. Found it and updated!
