### ISSUE TITLE
Use JS/TS files without shortcodes?

### ISSUE THREAD

**Issue by svicalifornia** [slinkity/slinkity#231]
I'm trying to use Slinkity to compile and import TS (or TSX) files, as I would using Vite.

My Slinkity project structure is something like this:

```
src/
  index.html
  app/
    index.ts
    SomeComponent.tsx
    OtherStuff.ts
    ...etc
```

I've tried to load `index.ts` from `index.html` in a variety of ways:

```html
<script src="/app/index.ts" type="module"></script>
<script src="/src/app/index.ts" type="module"></script>
<script src="../src/app/index.ts" type="module"></script>
```

…but the dev server 404's on all of those, and Rollup is unable to resolve any of those paths at build time.

Is it possible to reference a TS file like this, as I would in Vite, or are we limited to using shortcodes in Slinkity?

**Comment by bholmesdev** [comment]
Hey @svicalifornia! That's interesting, because loading TS files _should_ work exactly as Vite's documentation describes (even in Nunjucks or liquid files). Have you tried importing with an extension, i.e. `src="/src/app/index"`?

**Comment by bholmesdev** [comment]
Checking if you still have the issue @svicalifornia. Give the 1.0 canary a try at https://slinkity.dev/docs/quick-start and let me know!
