### ISSUE TITLE
V1 and Github Documentation

### ISSUE THREAD

**Issue by aaronstezycki** [slinkity/slinkity#237]
Just curious, as the documentation on the Github homepage is saying not to use the project in production and that it's still in alpha? 

Just wondering if that's still the case, and the github docs can be updated? I know there was a v1 launch post on twitter, so just looking for clarification? 

Also, just wanted to know which version of eleventy is currently suitable for use with slinkity? And whether we can update 11ty through npm? (although that might not be necessary if it's a dependency of slinkity). 11ty does seem to have some new nice features since v1.0.2 ~ v2 now.

Were there any breaking changes from Slinkity by updating to 11ty v2?

Thanks in advance. :)

**Comment by aaronstezycki** [comment]
Part answer: Looking at the install/getting started mentions installing via npm with `npm i slinkity  @11ty/eleventy@canary --save-dev` packages separately, so I'm assuming that 11ty can be updated freely without any issues to Slinkity.

**Comment by bholmesdev** [comment]
This is a good point! I'll confess this project has not been kept up-to-date for the past year, so I cannot guarantee compatibility between Slinkity and the latest versions of 11ty or Vite. The documentation lists the last versions tested.

As for the Slinkity project, I am sorry to say I will be stepping away and archiving the repository. I have updated the project README to reflect the current status. If the community would like to fork and keep Slinkity alive, all code is open and MIT licensed. I apologize for the radio silence, but I hope this clarifies everything!
