### ISSUE TITLE
CSS modules don't work when rendering components without hydration

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#43]
**Describe the bug**
When using `render='static'` on component pages or shortcodes, CSS modules aren't applied to the HTML template.

**Expected behavior**
I expect my CSS modules to get applied to the page as a `<style>` tag, similar to how hydrated components work.

**Additional context**
This is likely an issue with how we store styles alongside our components! At the moment, we only grab related resources for a component (including styles) when we apply our hydration loaders to the page. Ideally, we could apply styles for _all_ components on the page, even if no hydration loaders are present.

**Comment by nickrttn** [comment]
I'm still seeing this behavior in `slinkity@^1.0.0-canary.0`. For a reproduction, you can clone https://github.com/tus/tus.io/tree/11ty and run `npm run dev`.
