### ISSUE TITLE
Using Slinkity with existing repo - "could not auto-determine entry point..."

### ISSUE THREAD

**Issue by brycewray** [slinkity/slinkity#54]
**Describe the bug**
I took an existing repo, updated it to Eleventy 1.0.0-beta.2, changed it over from Tailwind to Sass, and then installed Slinkity and tried replacing the `package.json` Eleventy commands with Slinkity commands. On `npm run start`, I got the following error message (followed by many Vite-related items — e.g., `12:04:27 PM [vite] page reload` with the specific HTML file it's presumably building — which implied rendering success otherwise):

```bash
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.
[Info] Now serving on port 3000 🚀
[Info] Visit http://localhost:3000 in your favorite browser (that isn't IE 😉)
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling. (x2)
``` 

**To Reproduce**
1. In `package.json` scripting, replace the Eleventy commands with Slinkity commands as per the Slinkity docs.
2. Execute the proper script (e.g., `npm run start`).
3. Note the error message as the script fails.

**Expected behavior**
I expected the site to load in development mode.

**Screenshots**
N/A

**Versions**
 - OS: macOS 11.6
 - Browser: N/A because site didn't load.
 - Eleventy version: 1.0.0-beta.2
 - Slinkity version: 0.1.10

**Additional context**

**Comment by brycewray** [comment]
> @brycewray Ah thanks so much! Yes, this is known behavior actually that's safe to ignore. It's because we're starting up Vite before 11ty finishes processing your templates, so Vite doesn't know which dependencies it should bundle ahead of time.
> 
> Agreed this is _not_ ideal though. We'll try switching things around so Vite fires up on the right time!

@bholmesdev Understood, and thanks for the info. The site actually doesn't run at the current time...

```bash
[11ty] Copied 64 files / Wrote 177 files in 2.75 seconds (15.5ms each, v1.0.0-canary.41)
[11ty] Watching…
12:30:24 PM [vite] Internal server error: Unable to parse {"file":"/index.html","line":1,"column":3153}
```
... again, followed by a long string of minified HTML from the page I was trying to view in the browser. But, given what you're saying, I'll just wait until the project is a little further along. :)

**Comment by Holben888** [comment]
@brycewray Just fixed that warning!

> `(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.`

We now _delay_ starting the Vite server until the 11ty build is complete. This way, we can pre-bundle all your React components before you visit pages in the browser. This should also mean a much nicer development experience. You used to sit through multiple page loads while Vite processed everything in front of you. Now, it should be ready to go on start 😁

**Comment by Holben888** [comment]
> @Holben888 The repo is actually my regular site repo (https://github.com/brycewray/eleventy_site) but, given the earlier-reported issue above, I have removed Slinkity from it for now. If you'd like, I can clone that site to a test-only version and then re-install Slinkity. Let me know.

I'll also make a note to investigate this. If I replicate any bugs, I'll let you know so we can log a new bug report!
