### ISSUE TITLE
PostCSS support (and Tailwind as a sideeffect)

### ISSUE THREAD

**Issue by mistical2008** [slinkity/slinkity#63]
**Is your feature request related to a problem? Please describe.**
At that time slinkity lacks of `PostCSS` support. 
I know _sass_ supports a huge amount of things, but this is not the only solution to write styles. In my opinion `sass` or `scss` syntax with things like some monsterous mixins just _slows donw DX_. In _PostCSS_ you just install required plugin, set options and continue write your styles with some new magical property or function. In most cases I doesn't need all this `sass` things like nesting. I can add only a few needed number of this with _PostCSS_.
This time all that stuff like automatic fallbacks for properties, custom functions, _sass-like_ variables in plain _css_ and of course _Tailwind_ we can't use. Eleventy have _templating in markdown_, lets add the same functionality to _css_. 

**Describe the solution you'd like**
Implement slinkity as a plugin or config like in [61#](https://github.com/slinkity/slinkity/issues/61#issue-1034268146). Then we can pass _PostCSS_ config to _vites_ `css.postcss` options.
With plain _vite_ I usually add `postcss.config.js` path and all works fine. As soon this feature will be implemented then all `tailwind` stuff will be working automagically.

**Describe alternatives you've considered**
Check for an existence of `postcss.config.js` and pass this if exists to vites `css.postcss`. But `slinkity` config seems more viable solution than that.

**Additional context**
- [Tailwind installation and setup](https://tailwindcss.com/docs/installation#install-tailwind-via-npm)
- [Vite: css.postcss](https://vitejs.dev/config/#css-postcss)

**Comment by brycewray** [comment]
Has this been tried yet with `package.json` scripting using the Tailwind CLI? For example, the following works just fine in a normal Eleventy (beta) repo using Tailwind CSS 3.x (currently in alpha but totally fine in regular Eleventy):

```bash
tailwindcss --postcss -i src/assets/css/index.css -o _site/css/index.css --watch
```

...i.e., TWCSS takes the input CSS file and directly provides the result in the output location (`_site/css`), whereupon the HTML can reach it as `/css/index.css`, and Eleventy is fine with that. However, with Slinkity, I get the following (in addition to the CSS not being built) when I try to build:

```bash
[vite]: Rollup failed to resolve import "/css/index.css" from ".11ty-build-VTz13o/index.html".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

(In dev mode, the result is also aberrant with error messages like what's being reported in https://github.com/slinkity/slinkity/issues/84.)

So, given the earlier comments in this issue, should Tailwind be directed to put the CSS output somewhere else for Vite's benefit?

Reference repo:
https://github.com/brycewray/eleventy-slinkity-test

**Comment by Holben888** [comment]
@brycewray You'll likely want a new setup with Vite! In my configuration, I avoid using the Tailwind CLI entirely and let Vite do the PostCSS processing. This prevents the need for outputting CSS _at all._ You can simply reference the _input_ file that's importing all the Tailwind CSS pieces, and Vite will bundle the output on the other side.

I understand if this is confusing. I'm adding a more formalized documentation page on styling, but this combo of resources should get you there:
1. [Import styles directly using import aliases](https://slinkity.dev/docs/import-aliases/)
2. [An example project I built using Tailwind](https://github.com/holben888/spookity). Note that all we need is a `postcss.config.js`, which Vite picks up on automatically. Then you'll import the source `scss` file from the layout (see the `_includes` folder for that!)

**Comment by Holben888** [comment]
You raise a valuable point though: any scripts trying to output to the build directory will have a hard time during production builds! Ex. in your example, its building to a temporary build output that you can't predict when configuring the Tailwind CLI manually. This could mean some refactoring of your project's existing build process to leverage Vite more effectively.

**Comment by brycewray** [comment]
@Holben888 Appreciate the info (both comments). I had actually seen your Spookity repo but apparently didn't look at it sufficiently closely at the time re applicability to what I wanted to do. No big deal with a need for refactoring; am trying to learn The Right Way With Slinkity™. :) Thanks!

**Comment by brycewray** [comment]
@Holben888 Got it to work with a Spookity-style approach. 💯 [Repo](https://github.com/brycewray/eleventy-slinkity-test) now updated with working setup.

Just FYI, am still getting the following message multiple times during dev or build, but everything still works:

```bash
[Error] We failed to render components used in file src
We recommend trying to:
1. delete your output directory and restart the server / build
2. clear your node_modules and running a clean install with "npm i"

Visit https://slinkity.dev to review our changelogs!
Stacktrace:
Cannot read property 'insertAdjacentHTML' of null
```

**Comment by Holben888** [comment]
@brycewray  Hm... well that's not really acceptable in my book 😆 Seems to stem from an issue in our HTML parser, where it's _still_ trying to parse files that don't contain valid HTML. We check that the `.html` file is present before proceeding, but we've been discovering all kinds of edge cases with that. Do you happen to have XML in your repo?

**Comment by brycewray** [comment]
@Holben888 No XML in this repo AFAIK. In a regular Eleventy repo, I would (at least a `browserconfig.xml` file, if nothing else, plus code that builds an `index.xml` file for RSS), but not in this one.

**Comment by brycewray** [comment]
Also: on the image links failing, it appears it's not building the `/images` directory as per the Eleventy Image plugin (works OK in dev mode, but not in build) — but, as with the CSS, perhaps another refactor is in order, since the current shortcode writes an `/images` directory directly into the `_site` build directory. (Already brought this up in https://github.com/slinkity/slinkity/issues/74 as you may have seen by now.)

**Comment by Holben888** [comment]
@brycewray Gotcha, thanks for the deets! Let's move the convo to a new feature ticket or #74 for future reference, to avoid muddying this issue discussion. Super valuable feedback though 🙏
