### ISSUE TITLE
Support .tsx components

### ISSUE THREAD

**Issue by AndrewLeedham** [slinkity/slinkity#64]
**Is your feature request related to a problem? Please describe.**
I would like to use Slinkity with TypeScript React templates.

**Describe the solution you'd like**
Slinkity to see `.tsx` templates the same way it sees `.jsx`. From what I can tell this would just work out the box, as Vite already supports `.tsx`.

**Describe alternatives you've considered**
Just using `.jsx` with typedocs. However, I am looking to use Slinkity with [vanilla-extract](https://github.com/seek-oss/vanilla-extract) which requires full TypeScript.

**Additional context**
I played around with this in my own fork, and it seems to #justwork when swapping all the `.tsx` occurrences with `.jsx`. Although to support this properly I suppos we would need to register 2 plugins for each extension.

**Comment by Holben888** [comment]
> Although to support this properly I suppos we would need to register 2 plugins for each extension.

Yep, you're right on the money! This should be resolved as part of #55. We'll be sure to allow an array of accepted extensions for a given shortcode 👍
