### ISSUE TITLE
Fails to build XML or JSON feeds from eleventy-base-blog

### ISSUE THREAD

**Issue by AndrewLeedham** [slinkity/slinkity#65]
**Describe the bug**
The [eleventy-base-blog](https://github.com/11ty/eleventy-base-blog) has nunjucks templates that generate both XML and JSON feeds for RSS readers. When using Slinkity in place of eleventy these fail to build.

**To Reproduce**
1. Go to https://stackblitz.com/github/AndrewLeedham/eleventy-base-blog-slinkity
2. Run `npm run build` in the terminal.
3. See the issue.

**Expected behavior**
Slinkity to work out-the-box with the eleventy-starter-blog.

**Logs**
```bash
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > Having trouble writing template: .11ty-build-YLF9VP/sitemap.xml

`TemplateWriterWriteError` was thrown
[11ty] > Cannot read properties of null (reading 'insertAdjacentHTML')

`TypeError` was thrown:
[11ty]     TypeError: Cannot read properties of null (reading 'insertAdjacentHTML')
        at applyViteHtmlTransform (/home/projects/jvmiqqwvx.github/node_modules/slinkity/lib/plugin/index.js:99:31)
        at Object.eval (/home/projects/jvmiqqwvx.github/node_modules/slinkity/lib/plugin/index.js:161:22)
        at Template.runTransforms (/home/projects/jvmiqqwvx.github/node_modules/@11ty/eleventy/src/Template.js:512:38)
        at async Template.renderPageEntry (/home/projects/jvmiqqwvx.github/node_modules/@11ty/eleventy/src/Template.js:787:15)
        at async eval (/home/projects/jvmiqqwvx.github/node_modules/@11ty/eleventy/src/Template.js:803:21)
        at async Promise.all (index 0)
        at async Promise.all (index 1)
```

**(please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chrome 95
 - Version: 0.2.0

**Additional context**
Seems to me that Vite is assuming the template is outputting HTML, but in this case, it is either XML or JSON which it does not understand.

**Comment by Holben888** [comment]
Ah yep! This is because of a pretty nasty assumption we made: 11ty always outputs `.html` files, so we're safe to parse them serverside with a DOM parsing library (see #18). Should be a pretty simple try / catch at the parsing step before we transform. If you wanna poke around the code [over here](https://github.com/slinkity/slinkity/blob/e2124f76ebadc09d12661bd2b3c682a0bea58684/src/plugin/reactPlugin/2-pageTransform/toHydrationLoadersApplied.js#L46) and make a PR, be my guest! :grin:

**Comment by AndrewLeedham** [comment]
Makes sense. What should happen if we do find an error? Perhaps it should log something that is only visible in a debugging mode, since it is likely not an error most users will want to see, or should we be more smart about it and try and figure out what caused the error, or just suppress the error?

**Comment by Holben888** [comment]
@AndrewLeedham Great question! Well, you just reminded me that we never wired up 11ty's `DEBUG` flag to the Slinkity CLI. I think we can suppress the error, but leave a `TODO` to add 11ty debug output once it is supported. Also be sure to `return content` (untouched) if an error is found 👍

**Comment by endymion1818** [comment]
I'm still getting issues with this on 0.8.3, definitely happening with Slinkity since when I disable it, the feed.xml file is present in my build folder: https://github.com/endymion1818/deliciousreverie-11ty

**Comment by bholmesdev** [comment]
@endymion1818 Ah, are your XML files absent in the build output without any errors thrown? If so, I'd take a look [at our asset management docs!](https://slinkity.dev/docs/asset-management/#scenario-1%3A-permalinked-files) There's a small nuance to understand for passthrough copied and permalinked assets. Let me know if that solves the issue 👍

**Comment by endymion1818** [comment]
Hi Ben, yes I did, and also tried to move it to a `/public` folder, but this was still happening. No matter, I'm moving to Astro for all my sites so I'm going to wrap this up for now. Thanks for responding!

**Comment by bholmesdev** [comment]
Ah, sorry to hear that @endymion1818! Setting the permalink [to `public/feed.xml` here](https://github.com/endymion1818/deliciousreverie-11ty/blob/main/feed.xml.njk#L3) _should_ resolve the issue, though the use of JSON for frontmatter could be tripping things up. In any case, Astro's a great pick if you can afford the migration. See you around astro.build/chat ❤️

**Comment by endymion1818** [comment]
Thanks yes I think that's what I'm going to do. Appreciate your hard work on this, and Astro!
