### ISSUE TITLE
Add Prettier Config

### ISSUE THREAD

**Issue by AndrewLeedham** [slinkity/slinkity#73]
**Is your feature request related to a problem? Please describe.**
When contributing to the project I missed the section in Contributing.md that explains Prettier is in use (my bad). And submitted the code changes un-formatted before noticing the failing linting step.

**Describe the solution you'd like**
Move the prettier options from the ESLint config to a Prettier config at the root. Then new contributors who are aware of prettier will see the config straight away and plugins like `vscode-prettier` will pick up the config and allow for formatting on save etc if enabled.

**Describe alternatives you've considered**
- Running `npm run lint:fix` does fix the formatting issues, but that is a fairly manual process.
- `npm run lint:fix` could be a pre-commit hook, but that would not allow formatting on save or hooking in to the various editor formatting options.
- I could duplicate the prettier config into my user settings for this repo in vscode, but again that doesn't seem like an optimal solution.

**Comment by Holben888** [comment]
Ah yes, that's the setup I considered! But I've had a nicer development experience [adhering to Wes Bos' eslint setup](https://github.com/wesbos/eslint-config-wesbos) preferences. In short, he suggests running prettier via eslint to avoid setting up Prettier and eslint extensions in tandem (which has caused weirdness for me in the past!). So as long as:
1. You have the eslint VS Code extension installed (_not_ prettier)
2. You use this setting for formatting on save:
```js
"editor.codeActionsOnSave": {
  "source.fixAll": true
}
```

...you'll be covered! To streamline this, we could check in a `settings.json` under the `.vscode` directory to auto-configure this. We already do this to recommend the eslint extension for new contributors if none is installed.

**Comment by AndrewLeedham** [comment]
Oooh never knew you could do this. I might have to convert a bunch of my repos 😀

**Comment by Holben888** [comment]
> Oooh never knew you could do this. I might have to convert a bunch of my repos 😀

Going to change this to a "documentation" task. I'll add a note on that VS Code config to the `CONTRIBUTING` guide and add a prebuilt `.vscode/settings.json` to the repo 👍
