### ISSUE TITLE
Include 11ty Image Plugin for Documentation

### ISSUE THREAD

**Issue by ajcwebdev** [slinkity/slinkity#74]
### Is your feature request related to a problem? Please describe.

There is no current solution for including images in the Slinkity documentation.

### Describe the solution you'd like

Something that will let us easily drop in images without having to worry about manually optimizing for size or responsiveness.

### Describe alternatives you've considered

Ben suggested copying the image shortcode from [their docs](https://www.11ty.dev/docs/plugins/image/) as the easiest way to get this setup.

### Additional context

This is mostly a note for myself, but if anyone wants to take this on in the next week or two before I get to it then it should make for a pretty simple PR.

**Comment by brycewray** [comment]
Currently not able to get that Eleventy Image shortcode to work in production, although it works fine in dev mode; presume this is a case of needing to alter the existing code so it'll work with how Vite bundles assets, since the build doesn't include the specified output directory from Eleventy Image? ([Example repo](https://github.com/brycewray/eleventy-slinkity-test) and [demo](http://eleventy-slinkity-test.vercel.app/).)

**Comment by Holben888** [comment]
@brycewray Ah yes, this is a fundamental problem with our production builds. In short, we have a 2 stage build process right now:
1. Eleventy builds to a temporary directory
2. Vite builds _from_ that temporary directory to your specified output directory (`_site` in this example)

However, **Vite will _site before starting the build.** So if you want any eleventy plugins to build to the output directory, you'd need to build to that temporary directory that we generate instead. I'd prefer to keep this temporary directory flow since it avoids the double build directory problem (since we can safely delete the temp directory after a build).

I could see this being a problem for people's existing flows though! Ik we discussed CLI tools that _might_ try to build to the output directory as well, and it would be nice to avoid breaking those flows. I don't have a great solution right now but I'll definitely make a note of this. Feel free to make a separate "feature" ticket for this! Something like "support building to output dir via CLI tools and eleventy plugins."

**Comment by Holben888** [comment]
@brycewray Update: don't have time to verify, but you should be able to build your images somewhere that's _not_ the output dir (say `/img` at the base of your project), then bring it into the eleventy output [using a passthrough copy](https://www.11ty.dev/docs/copy/). Slightly more indirect and idk if it works with 11ty image, but that's what I've been using for static `asset` directories.

**Comment by brycewray** [comment]
> @brycewray Update: don't have time to verify, but you should be able to build your images somewhere that's _not_ the output dir (say `/img` at the base of your project), then bring it into the eleventy output [using a passthrough copy](https://www.11ty.dev/docs/copy/). Slightly more indirect and idk if it works with 11ty image, but that's what I've been using for static `asset` directories.

Yep, playing with that very thing now. (Re-reading not only the Eleventy Image docs but also the incredibly helpful https://www.aleksandrhovhannisyan.com/blog/eleventy-image-lazy-loading for inspiration.)Thanks!

**Comment by brycewray** [comment]
When I do `npm run build` locally, all the images build as they should, but builds to Vercel do not build the Eleventy Image-generated images. (FYI, I have set an env var, `NODE_VERSION`, to `14.16.0` to conform to what I have locally.)

From local build:
```bash
[11ty] Copied 32 files / Wrote 12 files in 0.38 seconds (31.7ms each, v1.0.0-beta.5)
vite v2.6.14 building for production...
✓ 13 modules transformed.
../_site/assets/Eleventy-favicon-16x16.dee4c8ab.png                                                   4.25 KiB
../_site/assets/Eleventy-favicon-32x32.a60b4f24.png                                                   4.59 KiB
../_site/assets/Typography-scr-cap-2-2018-10-16-600w.726d97f7.webp                                    5.94 KiB
../_site/assets/Typography-scr-cap-2-2018-10-16-900w.c9d01a29.webp                                    11.36 KiB
../_site/assets/Early-Web-font-grfx-1-2018-10-16_1218x1296-600w.136e4876.webp                         25.39 KiB
../_site/assets/screen-cap-from-Pippin-Williamson-s-page-builders-review_986x482-600w.4fdef145.webp   31.96 KiB
../_site/assets/Early-Web-font-grfx-1-2018-10-16_1218x1296-900w.049db167.webp                         38.11 KiB
../_site/assets/screen-cap-from-Pippin-Williamson-s-page-builders-review_986x482-900w.ef23ac53.webp   60.51 KiB
../_site/assets/Typography-scr-cap-2-2018-10-16-600w.895aa15b.jpeg                                    8.29 KiB
../_site/assets/Typography-scr-cap-2-2018-10-16-900w.5bb9356a.jpeg                                    18.46 KiB
../_site/assets/Early-Web-font-grfx-1-2018-10-16_1218x1296-600w.2cedb3ba.jpeg                         43.27 KiB
../_site/assets/screen-cap-from-Pippin-Williamson-s-page-builders-review_986x482-600w.f396119a.jpeg   47.08 KiB
../_site/assets/Typography-scr-cap-3-2018-10-16-600w.4e71d787.webp                                    11.60 KiB
../_site/assets/Early-Web-font-grfx-1-2018-10-16_1218x1296-900w.8b146def.jpeg                         72.69 KiB
../_site/assets/Typography-scr-cap-3-2018-10-16-900w.b716cd8c.webp                                    21.16 KiB
../_site/assets/screen-cap-from-Pippin-Williamson-s-page-builders-review_986x482-900w.894c2aa5.jpeg   87.09 KiB
../_site/assets/Typography-scr-cap-3-2018-10-16-600w.189a0244.jpeg                                    15.40 KiB
../_site/assets/Typography-scr-cap-3-2018-10-16-900w.4114d135.jpeg                                    30.65 KiB
../_site/assets/Typography-scr-cap-4-2018-10-16-600w.44107c07.webp                                    7.98 KiB
../_site/assets/Typography-scr-cap-4-2018-10-16-900w.57d42b6f.webp                                    14.44 KiB
../_site/assets/Typography-scr-cap-4-2018-10-16-600w.f2872aeb.jpeg                                    10.74 KiB
../_site/assets/Typography-scr-cap-4-2018-10-16-900w.9da80613.jpeg                                    22.09 KiB
../_site/about/index.html                                                                             4.46 KiB
../_site/index.html                                                                                   6.05 KiB
../_site/posts/1/index.html                                                                           10.60 KiB
../_site/posts/2019/06/post-6/index.html                                                              6.96 KiB
../_site/404.html                                                                                     3.58 KiB
../_site/posts/2019/03/post-4/index.html                                                              6.97 KiB
../_site/posts/2020/02/post-7/index.html                                                              6.73 KiB
../_site/posts/index.html                                                                             12.16 KiB
../_site/posts/2019/03/post-5/index.html                                                              6.96 KiB
../_site/posts/2018/10/post-2/index.html                                                              6.75 KiB
../_site/posts/2019/01/post-3/index.html                                                              6.61 KiB
../_site/posts/2018/10/post-1/index.html                                                              7.42 KiB
../_site/assets/index.cb7a8264.css                                                                    23.29 KiB / gzip: 5.28 Ki
```

From Vercel build:
```bash
[11ty] Copied 12 files / Wrote 12 files in 1.12 seconds (93.3ms each, v1.0.0-beta.5)
--
22:17:10.831 | vite v2.6.14 building for production...
22:17:10.965 | transforming...
22:17:11.684 | ✓ 13 modules transformed.
22:17:11.744 | rendering chunks...
22:17:11.781 | ../_site/assets/Eleventy-favicon-16x16.dee4c8ab.png   4.25 KiB
22:17:11.782 | ../_site/assets/Eleventy-favicon-32x32.a60b4f24.png   4.59 KiB
22:17:11.783 | ../_site/404.html                                     3.58 KiB
22:17:11.784 | ../_site/about/index.html                             4.46 KiB
22:17:11.784 | ../_site/index.html                                   6.05 KiB
22:17:11.784 | ../_site/posts/1/index.html                           10.60 KiB
22:17:11.784 | ../_site/posts/2019/03/post-4/index.html              6.97 KiB
22:17:11.784 | ../_site/posts/2019/03/post-5/index.html              6.96 KiB
22:17:11.784 | ../_site/posts/2019/06/post-6/index.html              6.96 KiB
22:17:11.785 | ../_site/posts/2020/02/post-7/index.html              6.73 KiB
22:17:11.785 | ../_site/posts/index.html                             12.16 KiB
22:17:11.785 | ../_site/posts/2018/10/post-2/index.html              6.71 KiB
22:17:11.786 | ../_site/posts/2019/01/post-3/index.html              6.57 KiB
22:17:11.786 | ../_site/posts/2018/10/post-1/index.html              7.29 KiB
22:17:11.788 | ../_site/assets/index.cb7a8264.css                    23.29 KiB / gzip: 5.28 KiB
```

(Also tried on Render with same settings; same result.)

Links same as before: [repo](https://github.com/brycewray/eleventy-slinkity-test) and [demo](https://eleventy-slinkity-test.vercel.app/).

**Comment by brycewray** [comment]
(Had a long comment here shortly ago about Eleventy Image-created images not building properly online, but now believe this is PEBKAC on my shortcode config's part and am trying to resolve. Just FYI in case you were investigating the now-deleted comment.)

**Comment by brycewray** [comment]
What (I think) I'm finding is that the Eleventy Image process — whether tried as async or as synchronous — works too slowly (or perhaps in the wrong sequence?) for the passthrough copy process to pick up the resulting output. It's apparently **not** a Slinkity/Vite issue, since the same occurs when I do it just through Eleventy. Because I'd always been sending the plugin-generated image files directly to the site output directory (`_site`) rather than using the passthrough copy method, hadn't encountered this up to now.

**Comment by Holben888** [comment]
@brycewray Hm, well that _is_ an issue for us to solve sadly. I think the delay in 11ty image processing is by-design, since it defers image generation to avoid delaying any `afterBuild` processes (like our Vite bundling process). I'll need to look into this more deeply to see whether Vite runs before or after all images are built. It it's before... that'll be a tough problem to solve 😬

**Comment by brycewray** [comment]
FWIW, I find Cloudinary's [React component](https://github.com/cloudinary/cloudinary-react) quite satisfactory for [testing purposes](https://eleventy-slinkity-test.vercel.app/posts/2018/10/post-2/) in the interim. :-) (Fortunately, I never come anywhere close to exceeding the limits of Cloudinary's free plan, but I realize that not everyone will find that a doable substitute for Eleventy Image.)

**Comment by Holben888** [comment]
@brycewray Just solved this issue! It was a pretty easy fix actually 🙃  So as you shared, doing something like:
1. outputting images to /img
2. passthrough copying /img into the build

...doesn't actually work (unless `/img` is populated by some previous build). The best choice is to dump images into the output dir directly
But how can we output to an output directory if it's `_site` in development and something like `11ty-build-DcNVBN` in production? Well, we can expose an environment variable!
Let's expose a variable called `ELEVENTY_BUILD_OUTPUT_DIR` to your eleventy config. You'll use it like so:
```js
await Image(src, {
    widths: [300, 600],
    formats: ["avif", "jpeg"],
    outputDir: path.join(process.env.ELEVENTY_BUILD_OUTPUT_DIR, 'img')
  });
```

...and bam! Images are put in the right place, picked up by Vite, and included in the final build. Just tested this myself 👍

Now I will say, you have to use the image shortcode in async mode. Using it in synchronous mode allows images to keep getting built even after 11ty's build is complete. This could mean you're building images to the 11ty build output when Vite is already doing its thing 😬

**Comment by Holben888** [comment]
First, I want to make a "gotchas coming from 11ty" page in our docs to properly explain this. This will come as part of #100. Once documentation and the flag are in, you should get images working no problem

**Comment by brycewray** [comment]
> First, I want to make a "gotchas coming from 11ty" page in our docs to properly explain this. This will come as part of #100. Once documentation and the flag are in, you should get images working no problem

Excellent! TY sir.

**Comment by Holben888** [comment]
Welp, we still don't have any images on our docs site to test this out 😆 I'll rename this issue to reflect our conversation: we want to build images to the intermediate dir so assets aren't lost. The above PR resolves that 👍
