### ISSUE TITLE
Add a leading file name/path to code blocks consistently

### ISSUE THREAD

**Issue by frankie-tech** [slinkity/slinkity#76]
**What feature were you trying to use?**

I was cruising the [config](https://slinkity.dev/docs/config/) documentation. 

**Where did our docs fail you?**

The [config](https://slinkity.dev/docs/config/) documentation had some code blocks that were missing the file name/path that they were related to.  Like the `vite.config.js` blocks didn't have the file name at the top, but the `slinkity.config.js` ones did.

**How can we improve?**

The leading file name/path helps me find what I'm looking for, but also helps me not lose track of where I am in the documentation. Having them there in general just helps, regardless of "context change" or only being in one context.

I created a [branch](https://github.com/frankie-tech/slinkity/tree/unify-file-name-in-code-blocks) that fixed the few I ran into, which I can make a PR for.

**Comment by ajcwebdev** [comment]
Awesome, I always like having these included in code blocks so thanks for cleaning this up for us. Feel free to open up a PR and we can get that merged for you.

**Comment by frankie-tech** [comment]
All set #81 😊
