### ISSUE TITLE
Vite import aliases don't work when building for production

### ISSUE THREAD

**Issue by bramsmulders** [slinkity/slinkity#77]
**Describe the bug**
Vite import aliases for SCSS files don't work when building for production.

**To Reproduce**
Ive added `<link rel="stylesheet" href="/@includes/styles/styles.scss" />` to my `base.njk` and this works beautifully in HMR mode. But when I try to build for production (`npx slinkity`) i get the following error:

```
[vite:load-fallback] Could not load /Users/bram/Developer/supple-kit/eleventy-supple-starter/.11ty-build-U0dn1s/_includes/styles/styles.scss (imported by .11ty-build-U0dn1s/index.html): ENOENT: no such file or directory, open '/Users/bram/Developer/supple-kit/eleventy-supple-starter/.11ty-build-U0dn1s/_includes/styles/styles.scss'
[11ty] Unhandled rejection in promise: (more in DEBUG output)
```

**Expected behavior**
I expect the build to succeed with a compiled CSS file. 

**(please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser: n/a
 - Version: `0.3.3`
 - NodeJS: `14.18.1`

**Comment by Holben888** [comment]
Ah, right you are! Looks like we mis-configured those aliases for production builds after a recent fix. Sorry for the regression.

Got it replicated on my machine and found a quick fix 👍 I'll also be fixing our new React pre-bundling, which might have caused you issues as well.

**Comment by Holben888** [comment]
Should be good-to-go on `v0.3.4`!

**Comment by bramsmulders** [comment]
Sick! Thnx for the swift response and fix! Your project is the best! ❤️
