### ISSUE TITLE
Should compile when `permalink` is `false`

### ISSUE THREAD

**Issue by bramsmulders** [slinkity/slinkity#82]
**Describe the bug**
In eleventy you can apply `permalink` with a `false` value to remove the rendering of the template. In Slinkity you check for `!outputPath.endsWith('.html')` in 2 places. booleans don't have `endsWith` as functions and thus building breaks. 

I've created an accompanying PR to fix the issue: #83

**Comment by Holben888** [comment]
Huh, I never knew about this 11ty deep-cut! Looks like a simple fix 👍
