### ISSUE TITLE
Multiple components on a page breaks the dev server

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#85]
**Describe the bug**
Using 2 or more component shortcodes on the same page with hydration (ex. 2 eagerly loaded components) breaks on server startup. Note: this does _not_ happen when you start with a single shortcode on the page, then add another shortcode **while the dev server is running.** It will only happen when:
- multiple shortcodes are present on the page before running `slinkity --serve`
- The Vite cache is fresh (i.e. `node_modules/.vite` is empty)

**Error**
```sh
`TemplateContentRenderError` was thrown

Eleventy:EleventyErrorHandler (error stack):
TemplateContentRenderError: Having trouble rendering liquid template ./src/index.md

[11ty] tag "react" not found, file:./src/index.md, line:3, col:1

`ParseError` was thrown

Eleventy:EleventyErrorHandler (error stack):
tag "react" not found, file:./src/index.md, line:3, col:1

   1| # ajcwebdev-slinkity
   2| 
>> 3| {% react 'components/Hello' %}
   4| 
   5| {% react 'components/Counter' %}

Eleventy:EleventyErrorHandler ParseError:

tag "react" not found, file:./src/index.md,
line:3, col:1 at ParseError.LiquidError [as constructor]

(/Users/ajcwebdev/ajcwebdev-slinkity/node_modules/liquidjs/dist/liquid.node.cjs.js:577:28)

[11ty] tag "react" not found

`AssertionError` was thrown:

Eleventy:EleventyErrorHandler (error stack):
AssertionError: tag "react" not found at new AssertionError (/Users/ajcwebdev/ajcwebdev-slinkity/node_modules/liquidjs/dist/liquid.node.cjs.js:653:28)
```

**To Reproduce**
1. Create any page template with multiple shortcodes:

```njk
{% react 'Component' %}
{% react 'Component2' %}
```

2. Start the dev server using `slinkity --serve` or `slinkity --serve --incremental`

Notice an error occurs.

**Expected behavior**
The build should continue without issues.

**Additional context**
The error hints at using the same import name across each hydration loader. This shouldn't cause any issues since they're wrapped in different `script` tags, but it looks like ESBuild smashes the script tags together during parsing.

Investigated using the latest `v0.13` for ESBuild and downgrading to Vite `v2.3`, but the issue seems to persist.

**Comment by Holben888** [comment]
cc @ajcwebdev

**Comment by Holben888** [comment]
Ack, just realized this was introduced by #54! This is the first time we started the Vite server _after_ the 11ty build instead of before. This exposed the wacky ESBuild issue.

**Comment by ajcwebdev** [comment]
What a wonderfully specific bug.

**Comment by Holben888** [comment]
> What a wonderfully specific bug.

What's a good bug without some details 😁
