### ISSUE TITLE
Community discord link invalid in CONTRIBUTING.md

### ISSUE THREAD

**Issue by patak-js** [slinkity/slinkity#87]
Hey 👋🏼

**Where did our docs fail you?**

The discord invite link https://discord.gg/AfZMRCg8 seems invalid, linked from [CONTRIBUTING.md#before-diving-into-the-code](https://github.com/slinkity/slinkity/blob/main/CONTRIBUTING.md#before-diving-into-the-code)

**Comment by ajcwebdev** [comment]
Hey @patak-js 👋! Great catch, not sure what that link goes to but it looks like 11ty's Discord link is https://discord.gg/GBkBy9u, I'll open up a PR to fix.

**Comment by patak-js** [comment]
Maybe you could get a permanent link to the #plugin-slinkity channel instead of the general 11ty discord invite?

**Comment by Holben888** [comment]
@patak-js @ajcwebdev Yeah, I generated a link that way using the "invite people" button on the channel! Starting to wonder if these links expire though... here's a fresh one at least: https://discord.gg/DRHrgSaU

**Comment by ajcwebdev** [comment]
Ahh interesting, I found a link as well that is totally different from that so that might be the case.

**Comment by ajcwebdev** [comment]
Okay you can specify when it expires.

https://support.discord.com/hc/en-us/articles/208866998-Invites-101

I'm using the one from the 11ty home page, so I'm guessing/hoping Zach has that one set to never expire.
