### ISSUE TITLE
The "to" argument must be of type string. Received type boolean (false)

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [slinkity/slinkity#89]
**Describe the bug**

I'm getting the following error when trying to migrate to Slinkity:

```
[11ty] > Having trouble writing template: false

`TemplateWriterWriteError` was thrown
[11ty] > The "to" argument must be of type string. Received type boolean (false)

`TypeError` was thrown:
[11ty]     TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type boolean (false)
        at new NodeError (node:internal/errors:371:5)
        at validateString (node:internal/validators:119:11)
        at relative (node:path:1192:5)
        at Object.<anonymous> (//path/to/project/node_modules/slinkity/lib/plugin/index.js:140:30)
        at Template.runTransforms (//path/to/project/node_modules/@11ty/eleventy/src/Template.js:527:38)
        at async Template.renderPageEntry (//path/to/project/node_modules/@11ty/eleventy/src/Template.js:802:15)
        at async //path/to/project/node_modules/@11ty/eleventy/src/Template.js:827:21
        at async Promise.all (index 0)
        at async Promise.all (index 6)
```

I suspect this is related to #84. I have the following `permalink: false`s:

- https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/blob/slinkity/src/_art/_art.json#L3
- https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/blob/slinkity/src/_licenses/_licenses.json#L2

Removing these allows the server to start.

**To Reproduce**
1. Clone https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com.
2. Check out the `slinkity` branch/
3. Run `yarn` to install dependencies.
4. Run `yarn serve` to start up the slinkity server.
5. Observe the error early on in the output.

**Expected behavior**
The error shouldn't occur 😄 

**(please complete the following information):**
 - OS: Windows 10 (WSL)
 - 11ty version: beta 5

**Comment by Holben888** [comment]
@AleksandrHovhannisyan Thanks for the heads up! Looks like this is related to our HTML parsing step. Will confirm before resolving the issue, but our next PR _should_ address this 👍

**Comment by Holben888** [comment]
@AleksandrHovhannisyan Welp, I was totally wrong about this! Turns out it's a much simpler issue: we have a checker for applying Vite middlewares that assumes `outputPath` is _always a string._ Hadn't considered the case where it's just the boolean false!

The culprit is [right here looks like](https://github.com/slinkity/slinkity/blob/main/src/plugin/index.js#L132). I'll see when I can get to it, but if you wanna open a PR with a fix yourself, I'm happy to review it 🙃 Might be worth extracting that function to make it unit test-able as well!

**Comment by AleksandrHovhannisyan** [comment]
@Holben888 Sounds good! Happy to contribute a fix. I'll take a look either tomorrow or over the weekend when I have time, if that's okay.

(If it's high priority, please don't hesitate to delegate it to someone else/knock it out yourself.)

**Comment by wommy** [comment]
i've just hit this problem myself

move the monorepo bork'd this

im guessing its [this](https://github.com/slinkity/slinkity/blob/main/packages/slinkity/eleventyConfig/index.js#L117-L133)?

**Comment by alexanderdavide** [comment]
I'm still facing the same issue. Any news regarding a fix or is there a temporary workaround I can use?

**Comment by Holben888** [comment]
@alexanderdavide Thanks for the callout! My suggested fix above should still apply if anyone wants to jump in. Otherwise, I’ll take a look at this by end of the week

**Comment by alexanderdavide** [comment]
@Holben888 Sorry but I don't quite get your fix suggestion. It may be because the given link is obsolete. Can you elaborate on this?

> The culprit is [right here looks like](https://github.com/slinkity/slinkity/blob/main/src/plugin/index.js#L132). I'll see when I can get to it, but if you wanna open a PR with a fix yourself, I'm happy to review it upside_down_face Might be worth extracting that function to make it unit test-able as well!

**Comment by wommy** [comment]
@Holben888 you move the src code so much, even my attempt at tracking it down, https://github.com/slinkity/slinkity/blob/main/packages/slinkity/eleventyConfig/index.js#L117-L133, seems to be out of date

@alexanderdavide my link still provides something very close to the original function

**Comment by wommy** [comment]
@Holben888 's solution ( i think )

https://github.com/slinkity/slinkity/blob/42f3ba8aa9c0770c284a4e5a09072c880eab73ab/packages/slinkity/utils/toSlashesTrimmed.js#L1-L11

this is erroring bc its not getting a string, right?

anyway i moved my offenders to `_includes/_content` and referenced them from there

**Comment by Holben888** [comment]
@alexanderdavide @wommy Ah, sorry everyone. I should've known about the broken link after our re-org for v0.6.0. [This is the line](https://github.com/slinkity/slinkity/blob/main/packages/slinkity/eleventyConfig/index.js#L106-L122) I meant to reference!

In short, we keep track of all generated pages in a map so we can access the output from a Browsersync middleware. This function assumes all output paths will be valid, so it needs to short-circuit on `false`. I'd need to double-check whether we need short circuiting from [the middleware](https://github.com/slinkity/slinkity/blob/main/packages/slinkity/eleventyConfig/applyViteHtmlTransform.js) as well (i.e. if no generated entry exists, don't serve anything).

Also want to share: yes, I'm aware that my availability has been spotty recently! I'm starting a new job this coming week, so I'm working to settle into a rhythm triaging issues. Just know I'm working to improve there 👍
