### ISSUE TITLE
Type Checking the source code

### ISSUE THREAD

**Issue by AndrewLeedham** [slinkity/slinkity#97]
**Is your feature request related to a problem? Please describe.**
I have been looking into how we can get better type safety into the JSDoc on the back of https://github.com/slinkity/slinkity/pull/93#discussion_r775607631 and thought I'd share my findings as a feature request.

**Describe the solution you'd like**
Linting/CI to catch JSDoc types that don't match up with the actual source code.

**Describe alternatives you've considered**
We could convert the whole repo to TypeScript, although from speaking with @bholmesdev I believe he wants to avoid that where possible.

**Findings**
I was initially looking into [eslint-plugin-jsdoc](https://www.npmjs.com/package/eslint-plugin-jsdoc), since currently types are stored there. However, it does not seem to support the TypeScript types with JavaScript code that we are using, it either supports basic JSDoc types or full TypeScript. Although, I do still think it would be a useful tool for normalising the formatting and applying rules to how JSDoc is written. We may have to manually configure things like TypeScript globals though (e.g: `Record`) because it does not know what that is, or just disable the type part of the plugin.

In order to actually check that all the typings work, it seems we would need to use the [`--checkJs`](https://github.com/microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files) option of `tsc`. Currently, Slinkity has a `tsconfig.json` which is pointing at the `defineConfig` types as that is the only user-facing code and produces declaration files to support that API. We would likely need to have 2 `tsconfig.json` files, one for type checking everything as another linting step, and another to generate the aforementioned declaration files.

**Comment by Holben888** [comment]
Thanks for investigating this! I think you're right about the JS Docs extension, but that's because we're _actually_ using the new [TS Doc standard instead](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html). Looks like there's a separate plugin for this: [eslint-plugin-tsdoc](https://www.npmjs.com/package/eslint-plugin-tsdoc). This comes with a few typescript friends as well. Worth trying out I think!

**Comment by AndrewLeedham** [comment]
> Thanks for investigating this! I think you're right about the JS Docs extension, but that's because we're _actually_ using the new [TS Doc standard instead](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html). Looks like there's a separate plugin for this: [eslint-plugin-tsdoc](https://www.npmjs.com/package/eslint-plugin-tsdoc). This comes with a few typescript friends as well. Worth trying out I think!

I did look at that, but it seems to require the ESLint TypeScript parser, and we aren't using TypeScript. Although on second thought perhaps that parser also infers types from JavaScript which is why it is required 🤔

**Comment by AndrewLeedham** [comment]
@Holben888 The TSDoc standard seems to be a subset of JSDoc specifically for TypeScript files, whereas the syntax with `@type` and `@typeref` etc are part of JSDoc. Meaning `eslint-plugin-tsdoc` does not do type checking: 
![image](https://user-images.githubusercontent.com/5557458/147613730-c03494e6-b06d-47ed-b2b0-770bc8495236.png)

It still seems to me that running `tsc` with `checkJs` is the only option.

**Comment by bholmesdev** [comment]
Latest follow-up in history: the codebase is getting updated to 100% TypeScript. This was an excellent experiment in JS-doc only setups, but found it cumbersome to work with and update overtime. I think going pure TS should make this more contributor friendly, and easier for myself to revisit while maintaining other open source projects ❤️
